CREATE TABLE "entity" (
	"id" text PRIMARY KEY NOT NULL,
	"shortId" text NOT NULL,
	"ownerId" text NOT NULL,
	"campaignId" text,
	"kind" text DEFAULT 'pc' NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"builderStep" integer DEFAULT 0 NOT NULL,
	"name" text NOT NULL,
	"portraitUrl" text,
	"pronouns" text,
	"notes" text,
	"attributes" jsonb,
	"affinities" jsonb,
	"vitals" jsonb,
	"skillPool" jsonb,
	"skills" jsonb,
	"talents" jsonb,
	"level" jsonb,
	"path" jsonb,
	"manualBonuses" jsonb,
	"archetypes" jsonb,
	"resources" jsonb,
	"exhaustion" jsonb,
	"mechanics" jsonb,
	"equipment" jsonb,
	"virtues" jsonb,
	"sparkLog" jsonb,
	"narrative" jsonb,
	"identityVersion" integer DEFAULT 0 NOT NULL,
	"vitalsVersion" integer DEFAULT 0 NOT NULL,
	"inventoryVersion" integer DEFAULT 0 NOT NULL,
	"progressionVersion" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "entity_shortId_unique" UNIQUE("shortId")
);
--> statement-breakpoint
ALTER TABLE "entity" ADD CONSTRAINT "entity_ownerId_user_id_fk" FOREIGN KEY ("ownerId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entity" ADD CONSTRAINT "entity_campaignId_campaign_id_fk" FOREIGN KEY ("campaignId") REFERENCES "public"."campaign"("id") ON DELETE set null ON UPDATE no action;