"use client"

import { unstable_rethrow, useRouter } from "next/navigation"
import { useMemo } from "react"

import { err, ok, type Result } from "@workspace/result"

import type {
  MutationEnvelope,
  MutationExecutorError,
  MutationTerminalOutcome,
  ProtocolIdentity,
} from "../authority"
import type {
  AnyMutationDefinition,
  MutationRefusalOf,
  ProtocolDefinition,
  ProtocolInvocation,
} from "../protocol"
import {
  createObservedRoot,
  createPredictedRootWithDeliveryErrorClassifier,
  RetryableDeliveryError,
  type ObservedRootOptions,
  type PredictedRootHook,
  type PredictedRootOptions,
} from "../react"
import type { RefreshAdapter } from "../refresh"
import type { AcceptedStamp } from "../revisions"

/** Grace period allowing a Server Action's RSC response to carry acceptance. */
export const ROUTER_ACCEPTANCE_GRACE_MS = 250

/**
 * Applies Next's control-flow classification at a catch boundary.
 * @internal Used by the generated Next predicted-root adapter.
 * @param error Unknown value caught while delivering a Server Action.
 * @returns Never returns when Next identifies framework control flow.
 * @throws Re-throws Next navigation or authorization control flow.
 */
export function rethrowNextControlFlow(error: unknown): void {
  unstable_rethrow(error)
}

type ProtocolMutation<Protocol> =
  Protocol extends ProtocolDefinition<string, infer Mutations>
    ? Mutations[number]
    : never

/**
 * The Server Action `createNextMutationAction` generates for one protocol.
 * The outcome carries a phantom {@link ProtocolIdentity}: a generated action
 * admits `unknown` envelopes, so its parameter cannot distinguish protocols.
 * The identity tag makes binding the wrong protocol's action a local type
 * error even when two protocols share a refusal shape.
 * @param envelope Parsed protocol envelope to deliver.
 * @returns A promise for the terminal authority result.
 */
export type NextMutationAction<
  Protocol extends ProtocolDefinition<string, readonly AnyMutationDefinition[]>,
> = (
  envelope: MutationEnvelope<ProtocolInvocation<Protocol>>
) => Promise<
  Result<
    Exclude<
      MutationTerminalOutcome<MutationRefusalOf<ProtocolMutation<Protocol>>>,
      { readonly kind: "denied" }
    >,
    MutationExecutorError
  > &
    ProtocolIdentity<Protocol["id"]>
>

/**
 * The golden-path form: a raw generated Server Action implies the standard
 * sender adapter, and the RSC binding implies the App Router refresh carrier
 * unless an explicit carrier overrides it. Application-owned facts — the
 * protocol and the invalidation transport — remain explicit.
 */
export interface NextActionPredictedRootOptions<
  Protocol extends ProtocolDefinition<string, readonly AnyMutationDefinition[]>,
> {
  readonly protocol: Protocol
  /** The Server Action generated by `createNextMutationAction`. */
  readonly action: NextMutationAction<Protocol>
  readonly refresh?: () => RefreshAdapter
  readonly invalidations?: PredictedRootOptions<Protocol>["invalidations"]
  readonly mutationListeners?: PredictedRootOptions<Protocol>["mutationListeners"]
  readonly recoveryListeners?: PredictedRootOptions<Protocol>["recoveryListeners"]
}

/**
 * Creates a predicted-root hook for a Next.js App Router surface.
 *
 * The action form is the standard path: it supplies the sender that preserves
 * Next control-flow throws and defaults refresh to `router.refresh()`. The
 * explicit `send` and `refresh` form remains available for snapshot carriers,
 * tests, and unusual delivery adapters. The generated action must use the same
 * protocol object as the root; its phantom protocol identity makes accidental
 * cross-protocol binding a type error. Omit `invalidations` when the surface
 * intentionally has no push transport.
 *
 * @param options Protocol and either generated action or explicit delivery dependencies.
 * @returns A predicted-root hook for the Next App Router.
 * @throws Framework control-flow errors are rethrown; ordinary delivery errors are classified by the root.
 */
export function createNextPredictedRoot<
  const Protocol extends ProtocolDefinition<
    string,
    readonly AnyMutationDefinition[]
  >,
>(
  options: NextActionPredictedRootOptions<Protocol>
): PredictedRootHook<Protocol>
export function createNextPredictedRoot<
  const Protocol extends ProtocolDefinition<
    string,
    readonly AnyMutationDefinition[]
  >,
>(options: PredictedRootOptions<Protocol>): PredictedRootHook<Protocol>
export function createNextPredictedRoot<
  const Protocol extends ProtocolDefinition<
    string,
    readonly AnyMutationDefinition[]
  >,
>(
  options:
    | NextActionPredictedRootOptions<Protocol>
    | PredictedRootOptions<Protocol>
): PredictedRootHook<Protocol> {
  const resolved: PredictedRootOptions<Protocol> =
    "action" in options
      ? {
          protocol: options.protocol,
          send: createNextMutationSender<Protocol>(options.action),
          refresh: options.refresh ?? useRouterRefresh,
          invalidations: options.invalidations,
          mutationListeners: options.mutationListeners,
          recoveryListeners: options.recoveryListeners,
        }
      : options
  return createPredictedRootWithDeliveryErrorClassifier(
    resolved,
    rethrowNextControlFlow
  )
}

/** Optional App Router refresh and invalidation dependencies for an observed root. */
export interface NextObservedRootOptions {
  readonly refresh?: () => RefreshAdapter
  readonly invalidations?: ObservedRootOptions["invalidations"]
}

/** An observed root whose canon arrives as RSC props through the App Router.
 * @param options Optional refresh and invalidation dependencies.
 * @returns An observed-root hook.
 */
export function createNextObservedRoot(options: NextObservedRootOptions = {}) {
  return createObservedRoot({
    refresh: options.refresh ?? useRouterRefresh,
    invalidations: options.invalidations,
  })
}

/**
 * Adapts a generated Server Action to the explicit predicted-root delivery
 * seam. Prefer the `action` form of {@link createNextPredictedRoot} for the
 * standard App Router carrier.
 * @param action Generated Server Action for one protocol.
 * @returns A sender adapter returning accepted stamps or typed refusals.
 */
export function createNextMutationSender<
  const Protocol extends ProtocolDefinition<
    string,
    readonly AnyMutationDefinition[]
  >,
>(
  action: NextMutationAction<Protocol>
): (
  envelope: MutationEnvelope<ProtocolInvocation<Protocol>>
) => Promise<
  Result<AcceptedStamp, MutationRefusalOf<ProtocolMutation<Protocol>>>
> {
  return async (envelope) => {
    const outcome = await action(envelope)
    if (!outcome.ok) {
      if (outcome.error.code === "contention") {
        throw new RetryableDeliveryError("mutation authority contention")
      }
      throw new Error(
        `mutation executor refused the envelope: ${outcome.error.code}`
      )
    }

    return outcome.value.kind === "accepted"
      ? ok(outcome.value.stamp)
      : err(outcome.value.error)
  }
}

/** Requests a new RSC payload through the App Router.
 * @returns A refresh adapter backed by `router.refresh()`.
 */
export function useRouterRefresh(): RefreshAdapter {
  const router = useRouter()

  return useMemo(
    () => ({
      acceptanceGraceMs: ROUTER_ACCEPTANCE_GRACE_MS,
      request: () => router.refresh(),
    }),
    [router]
  )
}
