"use client"

import { unstable_rethrow, useRouter } from "next/navigation"
import { useMemo } from "react"

import { err, ok, type Result } from "@workspace/result"

import type {
  MutationEnvelope,
  MutationExecutorError,
  MutationTerminalOutcome,
  ProtocolIdentity,
} from "../authority"
import type {
  AnyMutationDefinition,
  MutationRefusalOf,
  ProtocolDefinition,
  ProtocolInvocation,
} from "../protocol"
import {
  createObservedRoot,
  createPredictedRootWithDeliveryErrorClassifier,
  RetryableDeliveryError,
  type ObservedRootOptions,
  type PredictedRootHook,
  type PredictedRootOptions,
} from "../react"
import type { RefreshAdapter } from "../refresh"
import type { AcceptedStamp } from "../revisions"

export const ROUTER_ACCEPTANCE_GRACE_MS = 250

/** @internal Applies Next's control-flow classification at a catch boundary. */
export function rethrowNextControlFlow(error: unknown): void {
  unstable_rethrow(error)
}

type ProtocolMutation<Protocol> =
  Protocol extends ProtocolDefinition<string, infer Mutations>
    ? Mutations[number]
    : never

/**
 * The Server Action `createNextMutationAction` generates for one protocol.
 * The outcome carries a phantom {@link ProtocolIdentity}: a generated action
 * admits `unknown` envelopes and app wrappers preserve only the return type,
 * so the identity tag is what makes binding the wrong protocol's action a
 * local type error even when two protocols share a refusal shape.
 */
export type NextMutationAction<
  Protocol extends ProtocolDefinition<string, readonly AnyMutationDefinition[]>,
> = (
  envelope: MutationEnvelope<ProtocolInvocation<Protocol>>
) => Promise<
  Result<
    Exclude<
      MutationTerminalOutcome<MutationRefusalOf<ProtocolMutation<Protocol>>>,
      { readonly kind: "denied" }
    >,
    MutationExecutorError
  > &
    ProtocolIdentity<Protocol["id"]>
>

/**
 * The golden-path form: a raw generated Server Action implies the standard
 * sender adapter, and the RSC binding implies the App Router refresh carrier
 * unless an explicit carrier overrides it. Application-owned facts — the
 * protocol and the invalidation transport — remain explicit.
 */
export interface NextActionPredictedRootOptions<
  Protocol extends ProtocolDefinition<string, readonly AnyMutationDefinition[]>,
> {
  readonly protocol: Protocol
  /** The Server Action generated by `createNextMutationAction`. */
  readonly action: NextMutationAction<Protocol>
  readonly refresh?: () => RefreshAdapter
  readonly invalidations?: PredictedRootOptions<Protocol>["invalidations"]
}

/** Binds a predicted root to Next's thrown Server Action control flow. */
export function createNextPredictedRoot<
  const Protocol extends ProtocolDefinition<
    string,
    readonly AnyMutationDefinition[]
  >,
>(
  options: NextActionPredictedRootOptions<Protocol>
): PredictedRootHook<Protocol>
export function createNextPredictedRoot<
  const Protocol extends ProtocolDefinition<
    string,
    readonly AnyMutationDefinition[]
  >,
>(options: PredictedRootOptions<Protocol>): PredictedRootHook<Protocol>
export function createNextPredictedRoot<
  const Protocol extends ProtocolDefinition<
    string,
    readonly AnyMutationDefinition[]
  >,
>(
  options:
    | NextActionPredictedRootOptions<Protocol>
    | PredictedRootOptions<Protocol>
): PredictedRootHook<Protocol> {
  const resolved: PredictedRootOptions<Protocol> =
    "action" in options
      ? {
          protocol: options.protocol,
          send: createNextMutationSender<Protocol>(options.action),
          refresh: options.refresh ?? useRouterRefresh,
          invalidations: options.invalidations,
        }
      : options
  return createPredictedRootWithDeliveryErrorClassifier(
    resolved,
    rethrowNextControlFlow
  )
}

/** Watch-only sibling: defaults the App Router refresh carrier the same way. */
export interface NextObservedRootOptions {
  readonly refresh?: () => RefreshAdapter
  readonly invalidations?: ObservedRootOptions["invalidations"]
}

/** An observed root whose canon arrives as RSC props through the App Router. */
export function createNextObservedRoot(options: NextObservedRootOptions = {}) {
  return createObservedRoot({
    refresh: options.refresh ?? useRouterRefresh,
    invalidations: options.invalidations,
  })
}

/** Adapts the generated Server Action to a predicted root's delivery seam. */
export function createNextMutationSender<
  const Protocol extends ProtocolDefinition<
    string,
    readonly AnyMutationDefinition[]
  >,
>(
  action: NextMutationAction<Protocol>
): (
  envelope: MutationEnvelope<ProtocolInvocation<Protocol>>
) => Promise<
  Result<AcceptedStamp, MutationRefusalOf<ProtocolMutation<Protocol>>>
> {
  return async (envelope) => {
    const outcome = await action(envelope)
    if (!outcome.ok) {
      if (outcome.error.code === "contention") {
        throw new RetryableDeliveryError("mutation authority contention")
      }
      throw new Error(
        `mutation executor refused the envelope: ${outcome.error.code}`
      )
    }

    return outcome.value.kind === "accepted"
      ? ok(outcome.value.stamp)
      : err(outcome.value.error)
  }
}

/** Requests a new RSC payload through the App Router. */
export function useRouterRefresh(): RefreshAdapter {
  const router = useRouter()

  return useMemo(
    () => ({
      acceptanceGraceMs: ROUTER_ACCEPTANCE_GRACE_MS,
      request: () => router.refresh(),
    }),
    [router]
  )
}
