/**
 * PINNED v1 formula renderings (UNN-557 item 5) — GENERATED, do not edit.
 *
 * Produced by `apps/web/scripts/generate-formula-fixture.ts` running v1's
 * `hydrateFormula` + `foldDamageBonusesIntoFormula` over the full v1 skill
 * catalog. Once v1 is deleted (S4) this fixture IS the oracle: the
 * byte-identity test imports only v2 + this file. Regenerate only while v1
 * still exists, and only if the v1 catalog itself changes.
 *
 * Hydration scores: strength 2, magic 4, agility 1, luck 0 (asymmetric so
 * `st-or-ma` provably resolves to Magic). Bonus pair for `withBonuses`:
 * Frenzy `+3d4` (dice) and a flat zone `+2`, folded after the base term.
 */

export const FIXTURE_ATTRIBUTES = {
  strength: 2,
  magic: 4,
  agility: 1,
  luck: 0,
} as const

export interface PinnedTierRendering {
  skill: string
  band: string
  raw: string
  hydrated: string
  withBonuses: string
}

export interface PinnedFlatRendering {
  skill: string
  raw: string
  hydrated: string
}

export const PINNED_TIER_RENDERINGS: readonly PinnedTierRendering[] = [
  {
    skill: "agi",
    band: "1-10",
    raw: "1d4 + Ma",
    hydrated: "1d4 + 4",
    withBonuses: "1d4 + 3d4 + 2 + 4",
  },
  {
    skill: "agi",
    band: "11-19",
    raw: "1d8 + Ma",
    hydrated: "1d8 + 4",
    withBonuses: "1d8 + 3d4 + 2 + 4",
  },
  {
    skill: "agi",
    band: "20+",
    raw: "1d8 + Ma",
    hydrated: "1d8 + 4",
    withBonuses: "1d8 + 3d4 + 2 + 4",
  },
  {
    skill: "bash",
    band: "1-10",
    raw: "1d6 + St",
    hydrated: "1d6 + 2",
    withBonuses: "1d6 + 3d4 + 2 + 2",
  },
  {
    skill: "bash",
    band: "11-19",
    raw: "1d10 + St",
    hydrated: "1d10 + 2",
    withBonuses: "1d10 + 3d4 + 2 + 2",
  },
  {
    skill: "bash",
    band: "20+",
    raw: "1d10 + St",
    hydrated: "1d10 + 2",
    withBonuses: "1d10 + 3d4 + 2 + 2",
  },
  {
    skill: "blade-of-elec",
    band: "1-10",
    raw: "1d6 + St",
    hydrated: "1d6 + 2",
    withBonuses: "1d6 + 3d4 + 2 + 2",
  },
  {
    skill: "blade-of-elec",
    band: "11-19",
    raw: "1d10 + St",
    hydrated: "1d10 + 2",
    withBonuses: "1d10 + 3d4 + 2 + 2",
  },
  {
    skill: "blade-of-elec",
    band: "20+",
    raw: "1d10 + St",
    hydrated: "1d10 + 2",
    withBonuses: "1d10 + 3d4 + 2 + 2",
  },
  {
    skill: "blade-of-fire",
    band: "1-10",
    raw: "1d6 + St",
    hydrated: "1d6 + 2",
    withBonuses: "1d6 + 3d4 + 2 + 2",
  },
  {
    skill: "blade-of-fire",
    band: "11-19",
    raw: "1d10 + St",
    hydrated: "1d10 + 2",
    withBonuses: "1d10 + 3d4 + 2 + 2",
  },
  {
    skill: "blade-of-fire",
    band: "20+",
    raw: "1d10 + St",
    hydrated: "1d10 + 2",
    withBonuses: "1d10 + 3d4 + 2 + 2",
  },
  {
    skill: "blade-of-ice",
    band: "1-10",
    raw: "1d6 + St",
    hydrated: "1d6 + 2",
    withBonuses: "1d6 + 3d4 + 2 + 2",
  },
  {
    skill: "blade-of-ice",
    band: "11-19",
    raw: "1d10 + St",
    hydrated: "1d10 + 2",
    withBonuses: "1d10 + 3d4 + 2 + 2",
  },
  {
    skill: "blade-of-ice",
    band: "20+",
    raw: "1d10 + St",
    hydrated: "1d10 + 2",
    withBonuses: "1d10 + 3d4 + 2 + 2",
  },
  {
    skill: "blade-of-wind",
    band: "1-10",
    raw: "1d6 + St",
    hydrated: "1d6 + 2",
    withBonuses: "1d6 + 3d4 + 2 + 2",
  },
  {
    skill: "blade-of-wind",
    band: "11-19",
    raw: "1d10 + St",
    hydrated: "1d10 + 2",
    withBonuses: "1d10 + 3d4 + 2 + 2",
  },
  {
    skill: "blade-of-wind",
    band: "20+",
    raw: "1d10 + St",
    hydrated: "1d10 + 2",
    withBonuses: "1d10 + 3d4 + 2 + 2",
  },
  {
    skill: "bufu",
    band: "1-10",
    raw: "1d4 + Ma",
    hydrated: "1d4 + 4",
    withBonuses: "1d4 + 3d4 + 2 + 4",
  },
  {
    skill: "bufu",
    band: "11-19",
    raw: "1d8 + Ma",
    hydrated: "1d8 + 4",
    withBonuses: "1d8 + 3d4 + 2 + 4",
  },
  {
    skill: "bufu",
    band: "20+",
    raw: "1d8 + Ma",
    hydrated: "1d8 + 4",
    withBonuses: "1d8 + 3d4 + 2 + 4",
  },
  {
    skill: "cantata",
    band: "1-10",
    raw: "1d4 + Ma",
    hydrated: "1d4 + 4",
    withBonuses: "1d4 + 3d4 + 2 + 4",
  },
  {
    skill: "cantata",
    band: "11-19",
    raw: "1d8 + Ma",
    hydrated: "1d8 + 4",
    withBonuses: "1d8 + 3d4 + 2 + 4",
  },
  {
    skill: "cantata",
    band: "20+",
    raw: "1d12 + Ma",
    hydrated: "1d12 + 4",
    withBonuses: "1d12 + 3d4 + 2 + 4",
  },
  {
    skill: "cleave",
    band: "1-10",
    raw: "1d6 + St",
    hydrated: "1d6 + 2",
    withBonuses: "1d6 + 3d4 + 2 + 2",
  },
  {
    skill: "cleave",
    band: "11-19",
    raw: "1d10 + St",
    hydrated: "1d10 + 2",
    withBonuses: "1d10 + 3d4 + 2 + 2",
  },
  {
    skill: "cleave",
    band: "20+",
    raw: "1d10 + St",
    hydrated: "1d10 + 2",
    withBonuses: "1d10 + 3d4 + 2 + 2",
  },
  {
    skill: "critical-strike",
    band: "1-10",
    raw: "1d4 + St",
    hydrated: "1d4 + 2",
    withBonuses: "1d4 + 3d4 + 2 + 2",
  },
  {
    skill: "critical-strike",
    band: "11-15",
    raw: "1d8 + St",
    hydrated: "1d8 + 2",
    withBonuses: "1d8 + 3d4 + 2 + 2",
  },
  {
    skill: "critical-strike",
    band: "16+",
    raw: "1d8 + St",
    hydrated: "1d8 + 2",
    withBonuses: "1d8 + 3d4 + 2 + 2",
  },
  {
    skill: "cruel-attack",
    band: "1-10",
    raw: "1d6 + Ag",
    hydrated: "1d6 + 1",
    withBonuses: "1d6 + 3d4 + 2 + 1",
  },
  {
    skill: "cruel-attack",
    band: "11-19",
    raw: "1d10 + Ag",
    hydrated: "1d10 + 1",
    withBonuses: "1d10 + 3d4 + 2 + 1",
  },
  {
    skill: "cruel-attack",
    band: "20+",
    raw: "1d10 + Ag",
    hydrated: "1d10 + 1",
    withBonuses: "1d10 + 3d4 + 2 + 1",
  },
  {
    skill: "eiha",
    band: "1-10",
    raw: "1d4 + Ma",
    hydrated: "1d4 + 4",
    withBonuses: "1d4 + 3d4 + 2 + 4",
  },
  {
    skill: "eiha",
    band: "11-19",
    raw: "1d8 + Ma",
    hydrated: "1d8 + 4",
    withBonuses: "1d8 + 3d4 + 2 + 4",
  },
  {
    skill: "eiha",
    band: "20+",
    raw: "1d8 + Ma",
    hydrated: "1d8 + 4",
    withBonuses: "1d8 + 3d4 + 2 + 4",
  },
  {
    skill: "feint",
    band: "1-10",
    raw: "1d4 + Ag",
    hydrated: "1d4 + 1",
    withBonuses: "1d4 + 3d4 + 2 + 1",
  },
  {
    skill: "feint",
    band: "11-19",
    raw: "1d8 + Ag",
    hydrated: "1d8 + 1",
    withBonuses: "1d8 + 3d4 + 2 + 1",
  },
  {
    skill: "feint",
    band: "20+",
    raw: "1d8 + Ag",
    hydrated: "1d8 + 1",
    withBonuses: "1d8 + 3d4 + 2 + 1",
  },
  {
    skill: "flash-bomb",
    band: "1-10",
    raw: "1 + Ag",
    hydrated: "1 + 1",
    withBonuses: "1 + 3d4 + 2 + 1",
  },
  {
    skill: "flash-bomb",
    band: "11-19",
    raw: "1d4 + Ag",
    hydrated: "1d4 + 1",
    withBonuses: "1d4 + 3d4 + 2 + 1",
  },
  {
    skill: "flash-bomb",
    band: "20+",
    raw: "1d4 + Ag",
    hydrated: "1d4 + 1",
    withBonuses: "1d4 + 3d4 + 2 + 1",
  },
  {
    skill: "garu",
    band: "1-10",
    raw: "1d4 + Ma",
    hydrated: "1d4 + 4",
    withBonuses: "1d4 + 3d4 + 2 + 4",
  },
  {
    skill: "garu",
    band: "11-19",
    raw: "1d8 + Ma",
    hydrated: "1d8 + 4",
    withBonuses: "1d8 + 3d4 + 2 + 4",
  },
  {
    skill: "garu",
    band: "20+",
    raw: "1d8 + Ma",
    hydrated: "1d8 + 4",
    withBonuses: "1d8 + 3d4 + 2 + 4",
  },
  {
    skill: "kouha",
    band: "1-10",
    raw: "1d4 + Ma",
    hydrated: "1d4 + 4",
    withBonuses: "1d4 + 3d4 + 2 + 4",
  },
  {
    skill: "kouha",
    band: "11-19",
    raw: "1d8 + Ma",
    hydrated: "1d8 + 4",
    withBonuses: "1d8 + 3d4 + 2 + 4",
  },
  {
    skill: "kouha",
    band: "20+",
    raw: "1d8 + Ma",
    hydrated: "1d8 + 4",
    withBonuses: "1d8 + 3d4 + 2 + 4",
  },
  {
    skill: "memory-blow",
    band: "1-10",
    raw: "1d6 + Ag",
    hydrated: "1d6 + 1",
    withBonuses: "1d6 + 3d4 + 2 + 1",
  },
  {
    skill: "memory-blow",
    band: "11-19",
    raw: "1d10 + Ag",
    hydrated: "1d10 + 1",
    withBonuses: "1d10 + 3d4 + 2 + 1",
  },
  {
    skill: "memory-blow",
    band: "20+",
    raw: "1d10 + Ag",
    hydrated: "1d10 + 1",
    withBonuses: "1d10 + 3d4 + 2 + 1",
  },
  {
    skill: "psi",
    band: "1-10",
    raw: "1d4 + Ma",
    hydrated: "1d4 + 4",
    withBonuses: "1d4 + 3d4 + 2 + 4",
  },
  {
    skill: "psi",
    band: "11-19",
    raw: "1d8 + Ma",
    hydrated: "1d8 + 4",
    withBonuses: "1d8 + 3d4 + 2 + 4",
  },
  {
    skill: "psi",
    band: "20+",
    raw: "1d8 + Ma",
    hydrated: "1d8 + 4",
    withBonuses: "1d8 + 3d4 + 2 + 4",
  },
  {
    skill: "rampage",
    band: "1-10",
    raw: "1 + St",
    hydrated: "1 + 2",
    withBonuses: "1 + 3d4 + 2 + 2",
  },
  {
    skill: "rampage",
    band: "11-19",
    raw: "1d4 + St",
    hydrated: "1d4 + 2",
    withBonuses: "1d4 + 3d4 + 2 + 2",
  },
  {
    skill: "rampage",
    band: "20+",
    raw: "1d4 + St",
    hydrated: "1d4 + 2",
    withBonuses: "1d4 + 3d4 + 2 + 2",
  },
  {
    skill: "shield-arts",
    band: "1-10",
    raw: "1d4 + St",
    hydrated: "1d4 + 2",
    withBonuses: "1d4 + 3d4 + 2 + 2",
  },
  {
    skill: "shield-arts",
    band: "11-19",
    raw: "1d8 + St",
    hydrated: "1d8 + 2",
    withBonuses: "1d8 + 3d4 + 2 + 2",
  },
  {
    skill: "shield-arts",
    band: "20+",
    raw: "1d8 + St",
    hydrated: "1d8 + 2",
    withBonuses: "1d8 + 3d4 + 2 + 2",
  },
  {
    skill: "skewer",
    band: "1-10",
    raw: "1d6 + St",
    hydrated: "1d6 + 2",
    withBonuses: "1d6 + 3d4 + 2 + 2",
  },
  {
    skill: "skewer",
    band: "11-19",
    raw: "1d10 + St",
    hydrated: "1d10 + 2",
    withBonuses: "1d10 + 3d4 + 2 + 2",
  },
  {
    skill: "skewer",
    band: "20+",
    raw: "1d10 + St",
    hydrated: "1d10 + 2",
    withBonuses: "1d10 + 3d4 + 2 + 2",
  },
  {
    skill: "spirit-break",
    band: "1-10",
    raw: "1d6 + St",
    hydrated: "1d6 + 2",
    withBonuses: "1d6 + 3d4 + 2 + 2",
  },
  {
    skill: "spirit-break",
    band: "11-19",
    raw: "1d10 + St",
    hydrated: "1d10 + 2",
    withBonuses: "1d10 + 3d4 + 2 + 2",
  },
  {
    skill: "spirit-break",
    band: "20+",
    raw: "1d10 + St",
    hydrated: "1d10 + 2",
    withBonuses: "1d10 + 3d4 + 2 + 2",
  },
  {
    skill: "storm-thrust",
    band: "1-10",
    raw: "1d6 + St",
    hydrated: "1d6 + 2",
    withBonuses: "1d6 + 3d4 + 2 + 2",
  },
  {
    skill: "storm-thrust",
    band: "11-19",
    raw: "1d10 + St",
    hydrated: "1d10 + 2",
    withBonuses: "1d10 + 3d4 + 2 + 2",
  },
  {
    skill: "storm-thrust",
    band: "20+",
    raw: "1d10 + St",
    hydrated: "1d10 + 2",
    withBonuses: "1d10 + 3d4 + 2 + 2",
  },
  {
    skill: "tempest-slash",
    band: "1-10",
    raw: "1 + St",
    hydrated: "1 + 2",
    withBonuses: "1 + 3d4 + 2 + 2",
  },
  {
    skill: "tempest-slash",
    band: "11-19",
    raw: "1d4 + St",
    hydrated: "1d4 + 2",
    withBonuses: "1d4 + 3d4 + 2 + 2",
  },
  {
    skill: "tempest-slash",
    band: "20+",
    raw: "1d4 + St",
    hydrated: "1d4 + 2",
    withBonuses: "1d4 + 3d4 + 2 + 2",
  },
  {
    skill: "windblade",
    band: "1-10",
    raw: "1d6 + St",
    hydrated: "1d6 + 2",
    withBonuses: "1d6 + 3d4 + 2 + 2",
  },
  {
    skill: "windblade",
    band: "11-19",
    raw: "1d10 + St",
    hydrated: "1d10 + 2",
    withBonuses: "1d10 + 3d4 + 2 + 2",
  },
  {
    skill: "windblade",
    band: "20+",
    raw: "1d10 + St",
    hydrated: "1d10 + 2",
    withBonuses: "1d10 + 3d4 + 2 + 2",
  },
  {
    skill: "zio",
    band: "1-10",
    raw: "1d4 + Ma",
    hydrated: "1d4 + 4",
    withBonuses: "1d4 + 3d4 + 2 + 4",
  },
  {
    skill: "zio",
    band: "11-19",
    raw: "1d8 + Ma",
    hydrated: "1d8 + 4",
    withBonuses: "1d8 + 3d4 + 2 + 4",
  },
  {
    skill: "zio",
    band: "20+",
    raw: "1d8 + Ma",
    hydrated: "1d8 + 4",
    withBonuses: "1d8 + 3d4 + 2 + 4",
  },
]

export const PINNED_FLAT_RENDERINGS: readonly PinnedFlatRendering[] = [
  {
    skill: "dia",
    raw: "2d8 + Ma",
    hydrated: "2d8 + 4",
  },
  {
    skill: "divine-judgment",
    raw: "10d8",
    hydrated: "10d8",
  },
  {
    skill: "elemental-apocalypse",
    raw: "12d8",
    hydrated: "12d8",
  },
  {
    skill: "grand-heist",
    raw: "10d10",
    hydrated: "10d10",
  },
  {
    skill: "hammer-of-justice",
    raw: "8d10",
    hydrated: "8d10",
  },
  {
    skill: "media",
    raw: "2d8 + Ma",
    hydrated: "2d8 + 4",
  },
  {
    skill: "peerless-stonecleaver",
    raw: "12d10",
    hydrated: "12d10",
  },
  {
    skill: "phantom-tracer",
    raw: "12d10",
    hydrated: "12d10",
  },
  {
    skill: "showtime",
    raw: "6d8",
    hydrated: "6d8",
  },
  {
    skill: "wanton-destruction",
    raw: "12d10",
    hydrated: "12d10",
  },
]
